[package]
name = "oct-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
oct-cloud = { workspace = true }

assert_cmd = { workspace = true }
clap = { workspace = true }
tokio = { workspace = true }
predicates = { workspace = true }
serde = { workspace = true }
serde_derive = { workspace = true }
serde_json = { workspace = true }
tempfile = { workspace = true }
log = { workspace = true }
env_logger = { workspace = true }
toml = { workspace = true }
